- hosts: localhost
  connection: local
  roles:
    - role: dotfiles
    - role: vim
    - role: osx
      when: ansible_os_family == "Darwin"
    - role: homebrew
      when: ansible_os_family == "Darwin"
    - role: apt 
      when: ansible_distribution == 'Ubuntu'

