- name: Backup dotfiles
  backup:
    src: "~/.{{ item | basename }}"
  with_fileglob:
    - "files/*"

- name: Create dotfiles link
  file:
    src: "{{ item }}"
    dest: "~/.{{ item | basename }}"
    state: link
  with_fileglob:
    - "files/*"
