configure_bashcompletion() {
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
  fi
}

r_prompt() {
  printf '\U1F439 '
}

configure_history() {
  HISTSIZE=50000
}

configure_go() {
  export GOPATH=$HOME/.go
  export GO111MODULE=on
}

configure_prompt() {
  PS1='[\W]\$ '
}

configure_path() {
  export PATH=~/.go/bin:/usr/local/bin:$PATH
}

configure_java() {
  export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
}

configure_alias() {
  # For ls command
  alias ls='ls -G'
  alias ll='ls -lG'

  # For ruby
  alias bip='bundle install --path vendor/bundle'
  alias ber='bundle exec ruby'
  alias be='bundle exec'

  # For vim
  alias vi='vim'

  # For Python
  alias mypy='mypy --ignore-missing-imports'

  # For peco
  alias w='peco_tmux_window'
  alias p='peco_tmux_pane'

  # For fzf
  alias h='fzf_history'
  alias c='fzf_cd'

  # Screen Lock Comannd
  alias sl='/System/Library/CoreServices/"Menu Extras"/User.menu/Contents/Resources/CGSession -suspend'
}

configure_python() {
  export LC_ALL=ja_JP.UTF-8

  # For pyenv
  export PYENV_ROOT="$HOME/.pyenv"
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"

  # For pipenv
  export PIPENV_VENV_IN_PROJECT=1
}

configure_direnv() {
  eval "$(direnv hook bash)"
}

configure_fasd() {
  eval "$(fasd --init auto)"
}

fasd_exists() {
  which fasd > /dev/null
  if [ $? -ne 0 ]; then
    echo "Please install fasd"
    return 1
  fi
}

peco_exists() {
  which peco > /dev/null
  if [ $? -ne 0 ]; then
    echo "Please install peco"
    return 1
  fi
}

fzf_exists() {
  which fzf > /dev/null
  if [ $? -ne 0 ]; then
    echo "Please install fzf"
    return 1
  fi
}

fzf_history() {
  fzf_exists
  local res=$(history | awk '{$1=""; print}' | sort | uniq | fzf)
  READLINE_LINE=$res
  READLINE_POINT=${#res}

  # For osx
  if [ `uname` = "Darwin" ]; then
      ${READLINE_LINE}
  fi
}

fzf_cd() {
  fzf_exists
  fasd_exists
  local res=$(fasd -d | sort -rn | cut -c 12- | fzf)
  if [ -n "$res" ]; then
    cd $res
  else
    return 1
  fi
}

peco_history() {
  peco_exists
  local res=$(history | sort -r | awk '{$1 = ""; print}' | peco --query "$READLINE_LINE")
  if [ -n "$res" ]; then
    READLINE_LINE="$res"
    READLINE_POINT=${#res}
  else
    return 1
  fi
}

fzf_tmux_window() {
  fzf_exists
  tmux list-windows | fzf | awk -F':' '{print $1}' | xargs tmux select-window -t
}

fzf_tmux_pane() {
  fzf_exists
  tmux list-panes | fzf | awk -F':' '{print $1}' | xargs tmux select-pane -t
}

configure_aws() {
  complete -C '/usr/local/bin/aws_completer' aws
}

wifi() {
  local usage="Usage: ${FUNCNAME[0]} [on] [off]"

  if [ "$#" -ne 1 ]; then
    echo "$usage"
    return 1
  fi
  
  if [ "$1" == "on" ]; then 
    networksetup -setairportpower en0 on
  elif [ "$1" == "off" ]; then 
    networksetup -setairportpower en0 off
  else
    echo "$usage"
    return 1
  fi
}

eval_funcs() {
  # 関数名が"configure_*"の関数を実行
  local funcs=$(declare -f | grep -oE "configure_\w+")

  for i in $(echo ${funcs}) ; do
    eval ${i}
  done
}

eval_funcs
