- name: Update homebrew
  community.general.homebrew:
    update_homebrew: yes

- name: Add homebrew tap
  community.general.homebrew_tap:
    name: '{{ item.name }}'
    state: present
  with_items: '{{ homebrew_taps }}'

- name: Install homebrew packages
  community.general.homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
  with_items: '{{ homebrew_packages }}'

- name: Install homebrew cask packages
  community.general.homebrew_cask:
    name: '{{ item.name }}'
    state: installed
  with_items: '{{ homebrew_cask_packages }}'
