- name: Check python version {{ python_version }}
  shell: /usr/local/bin/pyenv versions | grep {{ python_version }}
  register: result
  changed_when: result.rc == 1

- name: Install python {{ python_version }}
  shell: /usr/local/bin/pyenv install {{ python_version }}
  when: result.rc == 1

- name: Set global python version
  shell: /usr/local/bin/pyenv global {{ python_version }}
  when: result.rc == 1
