homebrew_taps:
  - name: homebrew/cask-fonts

homebrew_packages:
  - name: vim
  - name: fasd
  - name: bash
  - name: tmux
  - name: git
  - name: bash-completion
  - name: binutils
  - name: hub
  - name: python
  - name: fzf
  - name: htop
  - name: watch
  - name: nkf
  - name: jq
  - name: awscli
  - name: rust

homebrew_cask_packages:
  - name: spectacle
  - name: zoom
  - name: visual-studio-code
  - name: kindle
  - name: hyperswitch
  - name: authy
  - name: alacritty
# - name: font-ricty-diminished
# - name: google-chrome
# - name: 1password
# - name: macvim
